---
title: All Beings Art
timezone: GMT
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
email: contact@allbeingsart.com
description:
instagram: allbeingsart
baseurl:
url:
markdown: kramdown
plugins:
  - jekyll-admin
